### ISSUE TITLE
Use Sass functions for convert `px` unit in stylesheets.

### ISSUE THREAD

**Issue by Yutna** [nimbl3/rails-templates#60]
Convert CSS unit from `px` to `rem` or `em` is a very tedious task. For improve more productive when you are working on stylesheets. `rails-templates` will provide `rem` and `em` Sass functions.

These functions will look like this when we are using.

**`rem()`**
```scss
.sample-1 {
  padding: rem(20px); // padding: 1.25rem;
}

.sample-2 {
  padding: rem(20px 16px); // padding: 1.25rem 1rem;
}

.sample-3 {
  padding: rem(20px 16px 32px); // padding: 1.25rem 1rem 2rem;
}

.sample-4 {
  padding: rem(20px 16px 32px auto); // padding: 1.25rem 1rem 2rem auto;
}
```

**`em()`**
```scss
.sample-1 {
  padding: em(20px); // padding: 1.25em;
}

.sample-2 {
  padding: em(20px 16px); // padding: 1.25em 1em;
}

.sample-3 {
  padding: em(20px 16px 32px); // padding: 1.25em 1em 2em;
}

.sample-4 {
  padding: em(20px 16px 32px auto); // padding: 1.25em 1em 2em auto;
}
```
