### ISSUE TITLE
Remove the port number after `:` in the docker-compose for test environment file.

### ISSUE THREAD

**Issue by Yutna** [nimbl3/rails-templates#71]
When we use this in Semaphore CI. We don't need to map the port number.

```yaml
# From
ports:
      - "5432:5432"
# To
ports:
      - "5432"
```

Please change this on both PosgreSQL and Redis port settings.
